### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by astrolemonade**
Hello!
I added Docker support for the website so it is easier to deploy. Suggestions and questions are welcomed.

### CODE REVIEW

**Comment by astrolemonade** [comment]
Seems like there are some issue with the `/article` route, I am trying to fix them now

**Comment by astrolemonade** [comment]
Now it should work as expected.

**Comment by hmdne** [comment]
Looks good to me. Though: if we are using 3.0 for development, why don't we also adjust it here:

https://github.com/ruby/TryRuby/blob/master/.github/workflows/deploy.yml#L18

**Comment by hmdne** [comment]
Added this and merging. Thank you! :D

**Pull request merged**
