### PR TITLE
Fix typos/spelling in Ru translation 🇷🇺

### PR DESCRIPTION
**Pull request by artkirienko**

### CODE REVIEW

**Comment by nikolaev-dev** [comment]
Thank you fixes!
Approved)

**Review by meh- — APPROVED** [review]

**Review by amalinovskii — APPROVED** [review]

**Review by vladzaets — APPROVED** [review]
I'm Russian native speaker, looks good

**Review by Makapoxa — APPROVED** [review]
looks good from Mother Russia

**Comment by artkirienko** [comment]
Hi @hsbt @amatsuda @easydatawarehousing! 👋 
Could you merge it, please?

**Comment by hsbt** [comment]
@artkirienko Thanks ❤️

**Pull request merged**
