### PR TITLE
Default to CRuby for https://try.ruby-lang.org/

### LINKED ISSUE #122: Make it clearer Opal is used on https://try.ruby-lang.org/
On https://try.ruby-lang.org/playground/ it is clear that Opal is the default, and one can choose CRuby.

But on the homepage, https://try.ruby-lang.org/ says nothing that Opal is used, and CRuby cannot be chosen.

This leads to confusion, e.g.:
* https://bugs.ruby-lang.org/issues/18609#note-7
* https://github.com/ruby/TryRuby/issues/78#issuecomment-1049959387

I think the best would be for the homepage to also have the "engine selector" (Opal/CRuby), so the homepage would be like the Playground page (but still without the docs)

### PR DESCRIPTION
**Pull request by eregon**
* Fixes https://github.com/ruby/TryRuby/issues/122

Unfortunately some tests fail, I'm not sure why.
For example, running `bundle exec rake spec` this one fails:
```
rspec './spec/tutorial_spec.rb[1:1:5]' # Tutorial in en has a working step 4 (Putting it differently)
```

### CODE REVIEW

**Comment by hmdne** [comment]
I have attempted it and mentioned it briefly in my last refactoring PR. The tests test the lessons which are, as of now, dependent on Opal idiosyncracies, like a particular syntax of errors. If we switched the default engine for lessons, many of them would stop working.

**Comment by eregon** [comment]
The CI shows 25 failures for 117 examples, it doesn't seem too bad.
And Tutorial step 4 fails for multiple languages, likely the same fix for all.
I think we should adapt the tutorial expectations/regexps/etc so they work with CRuby WASI.

Do you have any idea how to fix that Tutorial step 4 (Putting it differently)?
I tried to look into it but unfortunately the error output of specs is unhelpful and the regexp seemed OK (seems to accept any number, e.g not depending on a floating point number result which is Opal-specific), so it's not clear why the spec would fail.
Running the website locally that example behaved fine but indeed didn't show the green "label".

**Comment by hmdne** [comment]
Do note, that we only test first 5 examples for non-English languages on CI so it runs faster.

I *think* that the reason is as follows:

https://github.com/ruby/TryRuby/blob/master/app/try_ruby.rb#L400

`@output_buffer` for Opal may store single lines, while for Ruby-WASI it may store multiple lines at once. A fix could be to correct this behavior.

**Comment by hmdne** [comment]
This was my theory and it turned out to be correct. But it's quite a bit deeper:

As of now:

```ruby
puts "abc"
puts "abc"
```

gives for MRI the following `@output_buffer`: `["abc\nabc\n"]`
gives for Opal the following `@output_buffer`: `["abc\n", "abc\n"]`

This is for example the lesson "Putting it differently"

But this:

```ruby
print "abc\nabc\n"
```

gives for both the following `@output_buffer`: `["abc\nabc\n"]`

This is for example the lesson "Ready, Aim"

The patch I tried:

```diff
diff --git a/app/try_ruby.rb b/app/try_ruby.rb
index f38351c..9ae90a7 100644
--- a/app/try_ruby.rb
+++ b/app/try_ruby.rb
@@ -397,7 +397,7 @@ class TryRuby
     # Do not check the answer if there is no regexp matcher
     if @current_item && @current_item.answer
       # Get last line of output
-      value_to_check = @output_buffer.length > 0 && !@output_buffer.last.empty? ? @output_buffer.last.chomp : ''
+      value_to_check = @output_buffer.join.split("\n").reject(&:empty?).last
 
       # Check if output matches the defined answer regexp
       # and print status message
```

This gives us a way forward: we can force the `value_to_check` to denote only the last message then fix the lessons to rely on that.

Keep in mind, that this check is done on Opal, and Opal has another incompatibility - the regular expressions have JS semantics, so `^` means `\A` and `$` means `\z`.

**Comment by hmdne** [comment]
One nitpick - the JSON files are generated from respective files from `translations` directory. So those files need to be edited first and JSON will be generated from them.

**Comment by eregon** [comment]
Ah that's why the CI fails most likely but the specs pass locally, thanks for tip!

**Comment by eregon** [comment]
Is there any reason `source/try_ruby_*.json` are checked-in in the repo?
It seems confusing and error-prone to have such duplication.
These files can regenerated just fine if they don't exist.

Maybe it's for convenience of deploying to https://try.ruby-lang.org/ without extra commands in between?

**Comment by eregon** [comment]
Now all files should be in sync and the CI should pass.
(but it's taking some time to show up, https://www.githubstatus.com/ )

**Comment by hmdne** [comment]
> Is there any reason `source/try_ruby_*.json` are checked-in in the repo? It seems confusing and error-prone to have such duplication. These files can regenerated just fine if they don't exist.
> 
> Maybe it's for convenience of deploying to https://try.ruby-lang.org/ without extra commands in between?

Not sure. I agree it makes no sense to keep that.

> Now all files should be in sync and the CI should pass. (but it's taking some time to show up, https://www.githubstatus.com/ )

I'm running the full suite of tests locally and once they pass, I will merge.

**Comment by hmdne** [comment]
All good. Great work!

**Comment by eregon** [comment]
Thanks for review and merging.
I'm delighted https://try.ruby-lang.org/ now uses CRuby!

**Pull request merged**
