### PR TITLE
Add ru translation

### PR DESCRIPTION
**Pull request by nikolaev-dev**

### CODE REVIEW

**Comment by easydatawarehousing** [comment]
Hi Alexander, thanks for you excellent translation of tryruby. I ran all texts through google translate and it reads beautifully. Translating the reversed poem gives very amusing results :)

I have found a couple of small issues, could you please take a look at these?

Thanks,
Ivo


try_ruby_050.md - try_ruby_090.md, try_ruby_160.md, try_ruby_410.md  
If you want, you can translate Jimmy into some popular Russian name.

try_ruby_110.md  
While you were translating the English text changed a bit. To be more gender neutral, the boys/girls comparison was changed into apples/oranges. Maybe there is a common expression in Russian to indicate two fundamentally different things?

try_ruby_120.md  
Title is in english.

try_ruby_390.md  
Escaping of _get\_shakey_, remove spaces.

try_ruby_410.md  
Validation of correct answer. I think line 4 should be:  
answer: All's Well That Ends Well

try_ruby_410.md  
Line 22 </ sup>, remove spaces.

try_ruby_560.md  
Line 8, my_first_progam should be my_first_program (add r).

**Comment by nikolaev-dev** [comment]
> try_ruby_050.md - try_ruby_090.md, try_ruby_160.md, try_ruby_410.md
> If you want, you can translate Jimmy into some popular Russian name.
> 
Replace Jimmy to Ivan or Иван in try_ruby_50.md, try_ruby_60.md, try_ruby_70.md,  try_ruby_80.md, try_ruby_160.md
There is no "Jimmy" in 'translation/ru' :-) 

> try_ruby_110.md
> While you were translating the English text changed a bit. To be more gender neutral, the boys/girls comparison was changed into apples/oranges. Maybe there is a common expression in Russian to indicate two fundamentally different things?
> 
Fixed

> try_ruby_120.md
> Title is in english.
> 
Fixed

> try_ruby_390.md
> Escaping of get_shakey, remove spaces.
>
I've not understand you (

> try_ruby_410.md
> Validation of correct answer. I think line 4 should be:
> answer: All's Well That Ends Well
> 
fixed

> try_ruby_410.md
> Line 22 </ sup>, remove spaces.
> 
fixed in try_ruby_460.md

> try_ruby_560.md
> Line 8, my_first_progam should be my_first_program (add r).
> 
fixed

And 
Fixed answers in 
`ru/try_ruby_550.md` and `en/try_ruby_550.md`
`ru/try_ruby_390.md`
`ru/try_ruby_180.md`

**Comment by easydatawarehousing** [comment]
Thanks for your quick response. With try_ruby_390.md escaping I meant line 12. There spaces around the backslash.

I will have more time to look into tryruby this weekend and release your work.
Ivo

**Comment by nikolaev-dev** [comment]
Fixed in try_ruby_390.md 
Thank you for your review. It helps create better translation. 

Have a nice week 
Alex

**Comment by easydatawarehousing** [comment]
Thanks again for adding this translation,
Ivo

**Comment by nikolaev-dev** [comment]
Hi!
Can you tell, when you are going to deploy master on production? 

Now there are no Russian translation on https://ruby.github.io/TryRuby/

**Comment by easydatawarehousing** [comment]
Hi,

In this repo it is already available (https://easydatawarehousing.github.io/TryRuby/). I have emailed @hsbt with the request to sync the fork of this repo that actually serves https://ruby.github.io/TryRuby/

I hope this will be done soon.
Ivo

**Comment by hsbt** [comment]
Hi, I started to coordinate to transfer this repository to the ruby organization. Stay tuned.

**Comment by easydatawarehousing** [comment]
Done !

**Review by artkirienko — COMMENTED** [review]
Translation looks good! 🎉 👍  
but I've found some typos/spelling errors, so I opened a PR on it

👉 https://github.com/ruby/TryRuby/pull/50

**Pull request merged**
