### PR TITLE
Added Ukrainian translation

### PR DESCRIPTION
**Pull request by andriipalchik**
Hi! I'm Andrii and I've translated TryRuby to my native language. I tried to follow your guidelines for translation and now I'd like to add it to the master branch. The name of the language in the namepicker should be "Українська" as in "Русский" or "English". Cheers!

### CODE REVIEW

**Comment by andriipalchik** [comment]
I don't know how long does it usually take to add a translation, but I've done everything right, and nothing's happend yet. Weird...

**Review by easydatawarehousing — APPROVED** [review]

**Comment by easydatawarehousing** [comment]
Hi Andrii, again my apologies that you translation was not picked up sooner. I think your translation looks great (at least google translate does a very decent translation back into English).
To make the new language available it should be added to source/index.html.markdown. And you may want to add it to the `get_language` method in source/javascripts/try_ruby.js.rb, so a webbrowser automatically selects the Ukranian version.
And if you want, you can add your name to source/about.html.markdown translations section.

**Comment by andriipalchik** [comment]
Thank you sir for checking my translation. I just did what you
recommended, so I hope you'll add it this time. Cheers!

**Comment by andriipalchik** [comment]
Thank you for everything. Now, sorry to bother you, but I just looked at
the translation with a fresh eye and noticed some minor errors (last time I
saw the code in February), so I've corrected them and started a new pull
request. If you have time https://github.com/ruby/TryRuby/pull/87

чт, 1 жовт. 2020 о 10:25 Ivo Herweijer <notifications@github.com> пише:

**Pull request merged**
