### PR TITLE
New Design

### PR DESCRIPTION
**Pull request by sunny**
Hey maintainers! This is me again, this time with a larger piece: an updated design.

Important changes in this PR:

- New fonts, colors and look and feel inspired by [this version](https://user-images.githubusercontent.com/132/144718210-04eb3278-9480-4180-b724-66940f6df8a3.png) of Try Ruby
- Foxes illustration on the first page, from _why’s poignant guide <3
- New [language icon](https://en.wikipedia.org/wiki/Language_Icon), moved inside the menu
- Removed Glyphicons
- Put editor before the output to make it more intuitive
- Grouped `Back` and `Next` around the lesson selector, to make the dependency clearer.
- Removed "Clear" button to declutter the interface a bit
- Update Bootstrap to Bootstrap 5 & remove its jQuery dependency
- Removed HAML templates in favor of simpler ERB. This also helps unify the different templates as some were already using ERB.

I understand that these can be a lot of changes in one pull-request. I’d be happy to split it in multiple steps if that makes it easier to reason about.

## Before

Screenshot of the Try Ruby home with the current design

## After

Screenshot of the Try Ruby home with a new design

### CODE REVIEW

**Comment by hsbt** [comment]
I'm +1 to the new design. 

@easydatawarehousing Do you have any opinion about this design?

**Comment by hmdne** [comment]
Thank you for this! :D Looks great in my opinion. I reviewed the whole patchset and found no issues. I think I will just merge it.

**Comment by hmdne** [comment]
@hsbt We replied at the exact same time and I just noticed. I will wait for your approval in the future for issues of this kind.

**Comment by easydatawarehousing** [comment]
@sunny @hmdne @hsbt Design looks great to me. Thanks for the update!

**Comment by hsbt** [comment]
@hmdne No problem. Thanks for your works.

**Pull request merged**
