### PR TITLE
Fully translated to Brazilian Portuguese

### PR DESCRIPTION
**Pull request by ricardovsilva**
Fully translated to Brazilian Portuguese. But it's was only reviewed by me. So is a good idea put someone more to work on that (I already asked a friend of mine to do that), and put some kind of message telling users that this translation is in Beta stage.
Looking the entire TryRuby, this is very very smart, congrats for idea.

### CODE REVIEW

**Comment by ricardovsilva** [comment]
Fully translated to Brazilian-Portuguese

**Comment by easydatawarehousing** [comment]
Amazing work ! Thanks. I tried your translation, using a clone of your repo. Looking good.

Don't forget to edit collector.rb:139
      Collector.new('translations/pt-br/try_ruby_*.md', 'source/try_ruby_pt-br.json').collect

Source javascripts:122
      when 'pt-br'
        language = 'pt-br'

And source/index.html.md:22
              <option value="pt-br">Portuguese</option>

And of course in translations/pt-br/README.md you can replace all names with your own.

Best regards,
Ivo

**Comment by ricardovsilva** [comment]
Done, is that now ready to deploy?

**Comment by ricardovsilva** [comment]
I fixed the errors you pointed in #12 . Can you take a look?

**Pull request merged**
